### ISSUE TITLE
Video signal lost when the app is coming from the background to the foreground on Android

### ISSUE THREAD

**Issue by youssmak** [voxeet/voxeet-cordova-conferencekit#8]
On Android:
The conf call continue to work when the app is in the background
"Waiting for users" is shown when our app is coming from the background to the foreground.

Everything works fine on iOS.

**Comment by codlab** [comment]
Without being able to reproduce it would be convenient to have the following filled up :
```
# Issue Template

When opening issues in involved projects. Please copy and follow those guidelines :

## Expected Behavior


## Actual Behavior


## Steps to Reproduce the Problem

### Workflow

  1.
  2.
  3.

### Minimalistic code

_Please provide a link to a repository showing specifically the issue. It should only have the minimal footprint of your own implementation - something which does not requires any NDA_

## Specifications

  - Version:
    - _for each libraries : name -> version`
  - Platform: _name and version of the platform where the issue appears_
  - Subsystem: _in case of specific modified environment, please provide any relevant information_
  - Hardware:
    - _for each specific hardware element on the system, a list of their name->(driver->version)_
```
